"""Add CarInfo table and link Car to CarInfo

Revision ID: 3435ea5983ad
Revises: 90c4f4b35f51
Create Date: 2025-12-09 13:27:08.892431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3435ea5983ad'
down_revision: Union[str, None] = '90c4f4b35f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('api_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_car_info_id', 'car_info', ['id'], unique=False)
    op.create_index('ix_car_info_vin', 'car_info', ['vin'], unique=True)
    op.add_column('cars', sa.Column('car_info_id', sa.Integer(), nullable=True))
    op.create_index('ix_cars_car_info_id', 'cars', ['car_info_id'], unique=False)
    op.create_foreign_key(None, 'cars', 'car_info', ['car_info_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_index('ix_cars_car_info_id', table_name='cars')
    op.drop_column('cars', 'car_info_id')
    op.drop_index('ix_car_info_vin', table_name='car_info')
    op.drop_index('ix_car_info_id', table_name='car_info')
    op.drop_table('car_info')
    # ### end Alembic commands ###

