"""Remove unique constraint from VIN

Revision ID: 90c4f4b35f51
Revises: 6434218706c0
Create Date: 2025-12-09 13:10:59.661533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c4f4b35f51'
down_revision: Union[str, None] = '6434218706c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_vin'), table_name='cars')
    op.create_index(op.f('ix_cars_vin'), 'cars', ['vin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_vin'), table_name='cars')
    op.create_index(op.f('ix_cars_vin'), 'cars', ['vin'], unique=True)
    # ### end Alembic commands ###

