"""add manuals and manual_chunks tables

Revision ID: a1b2c3d4e5f6
Revises: 71288ed7d640
Create Date: 2026-01-28 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '71288ed7d640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manuals',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuals_id'), 'manuals', ['id'], unique=False)
    op.create_index(op.f('ix_manuals_car_id'), 'manuals', ['car_id'], unique=False)
    
    op.create_table('manual_chunks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('manual_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manual_id'], ['manuals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('embedding_id')
    )
    op.create_index(op.f('ix_manual_chunks_id'), 'manual_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_manual_chunks_manual_id'), 'manual_chunks', ['manual_id'], unique=False)
    op.create_index(op.f('ix_manual_chunks_embedding_id'), 'manual_chunks', ['embedding_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_chunks_embedding_id'), table_name='manual_chunks')
    op.drop_index(op.f('ix_manual_chunks_manual_id'), table_name='manual_chunks')
    op.drop_index(op.f('ix_manual_chunks_id'), table_name='manual_chunks')
    op.drop_table('manual_chunks')
    op.drop_index(op.f('ix_manuals_car_id'), table_name='manuals')
    op.drop_index(op.f('ix_manuals_id'), table_name='manuals')
    op.drop_table('manuals')
    # ### end Alembic commands ###
